version: '2'
services:
  web:
    image: yurifl/node
    command: ember server --watcher polling --environment development
    ports:
      - 4200:4200
      - 49152:49152
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bower_components:/app/bower_components
    environment:
      EMBER_ENV: development

volumes:
  node_modules:
    external: true
  bower_components:
    external: true
